### ISSUE TITLE
Breaking on Rails 6.0.3

### ISSUE THREAD

**Issue by bemky** [malomalo/sunstone#20]
Getting the following error when upgrading to 6.0.3.1

```ruby
ActionView::Template::Error (undefined method `associated_predicate_builder' for #<ActiveRecord::PredicateBuilder:0x00007fd47840af98>):
    35:           can_cache = can_cache && !record.send(association.foreign_key).nil?
    36:         end
    37:         json.cache_if!(can_cache, can_cache ? association_cache_key(record, inc, subinc) : nil) do
    38:           value = record.send(inc)
    39:           if value.nil?
    40:             json.set! inc, nil
    41:           else
  
sunstone (d79c5d2b5050) ext/active_record/finder_methods.rb:9:in `block in expand_from_hash'
sunstone (d79c5d2b5050) ext/active_record/finder_methods.rb:7:in `each'
sunstone (d79c5d2b5050) ext/active_record/finder_methods.rb:7:in `flat_map'
sunstone (d79c5d2b5050) ext/active_record/finder_methods.rb:7:in `expand_from_hash'
activerecord (6.0.3.1) lib/active_record/relation/predicate_builder.rb:21:in `build_from_hash'
activerecord (6.0.3.1) lib/active_record/relation/where_clause_factory.rb:19:in `build'
activerecord (6.0.3.1) lib/active_record/relation/query_methods.rb:656:in `where!'
activerecord (6.0.3.1) lib/active_record/associations/association_scope.rb:156:in `apply_scope'
activerecord (6.0.3.1) lib/active_record/associations/association_scope.rb:65:in `last_chain_scope'
activerecord (6.0.3.1) lib/active_record/associations/association_scope.rb:122:in `add_constraints'
activerecord (6.0.3.1) lib/active_record/associations/association_scope.rb:29:in `scope'
activerecord (6.0.3.1) lib/active_record/associations/association_scope.rb:7:in `scope'
activerecord (6.0.3.1) lib/active_record/associations/association.rb:225:in `association_scope'
activerecord (6.0.3.1) lib/active_record/associations/association.rb:101:in `scope'
activerecord (6.0.3.1) lib/active_record/associations/association.rb:204:in `find_target'
activerecord (6.0.3.1) lib/active_record/associations/singular_association.rb:39:in `find_target'
activerecord (6.0.3.1) lib/active_record/associations/association.rb:164:in `load_target'
activerecord (6.0.3.1) lib/active_record/associations/association.rb:65:in `reload'
activerecord (6.0.3.1) lib/active_record/associations/singular_association.rb:9:in `reader'
activerecord (6.0.3.1) lib/active_record/associations/builder/association.rb:100:in `avatar'
standardapi (2b3ec1e8ac2a) lib/standard_api/views/application/_record.streamer:38
turbostreamer (d6c4eca5f284) lib/turbostreamer/template.rb:110:in `cache_if!'
standardapi (2b3ec1e8ac2a) lib/standard_api/views/application/_record.streamer:37
standardapi (2b3ec1e8ac2a) lib/standard_api/views/application/_record.streamer:9:in `each'
standardapi (2b3ec1e8ac2a) lib/standard_api/views/application/_record.streamer:9
turbostreamer (d6c4eca5f284) lib/turbostreamer.rb:58:in `block in object!'
turbostreamer (d6c4eca5f284) lib/turbostreamer.rb:358:in `_scope'
turbostreamer (d6c4eca5f284) lib/turbostreamer.rb:58:in `object!'
standardapi (2b3ec1e8ac2a) lib/standard_api/views/application/_record.streamer:1
actionview (6.0.3.1) lib/action_view/base.rb:274:in `_run'
actionview (6.0.3.1) lib/action_view/template.rb:185:in `block in render'
activesupport (6.0.3.1) lib/active_support/notifications.rb:182:in `instrument'
actionview (6.0.3.1) lib/action_view/template.rb:385:in `instrument_render_template'
actionview (6.0.3.1) lib/action_view/template.rb:183:in `render'
actionview (6.0.3.1) lib/action_view/renderer/partial_renderer.rb:357:in `block in render_partial'
actionview (6.0.3.1) lib/action_view/renderer/abstract_renderer.rb:88:in `block in instrument'
activesupport (6.0.3.1) lib/active_support/notifications.rb:180:in `block in instrument'
activesupport (6.0.3.1) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (6.0.3.1) lib/active_support/notifications.rb:180:in `instrument'
actionview (6.0.3.1) lib/action_view/renderer/abstract_renderer.rb:87:in `instrument'
actionview (6.0.3.1) lib/action_view/renderer/partial_renderer.rb:346:in `render_partial'
actionview (6.0.3.1) lib/action_view/renderer/partial_renderer.rb:317:in `render'
actionview (6.0.3.1) lib/action_view/renderer/renderer.rb:65:in `render_partial_to_object'
actionview (6.0.3.1) lib/action_view/renderer/renderer.rb:27:in `render_to_object'
actionview (6.0.3.1) lib/action_view/renderer/renderer.rb:22:in `render'
actionview (6.0.3.1) lib/action_view/helpers/rendering_helper.rb:34:in `block in render'
actionview (6.0.3.1) lib/action_view/base.rb:304:in `in_rendering_context'
actionview (6.0.3.1) lib/action_view/helpers/rendering_helper.rb:30:in `render'
turbostreamer (d6c4eca5f284) lib/turbostreamer/template.rb:158:in `_render_partial_with_options'
turbostreamer (d6c4eca5f284) lib/turbostreamer/template.rb:34:in `partial!'
app/views/sessions/_session.streamer:8
turbostreamer (d6c4eca5f284) lib/turbostreamer.rb:358:in `_scope'
turbostreamer (d6c4eca5f284) lib/turbostreamer.rb:154:in `set!'
app/views/sessions/_session.streamer:7
turbostreamer (d6c4eca5f284) lib/turbostreamer.rb:58:in `block in object!'
turbostreamer (d6c4eca5f284) lib/turbostreamer.rb:358:in `_scope'
turbostreamer (d6c4eca5f284) lib/turbostreamer.rb:58:in `object!'
app/views/sessions/_session.streamer:1
actionview (6.0.3.1) lib/action_view/base.rb:274:in `_run'
actionview (6.0.3.1) lib/action_view/template.rb:185:in `block in render'
activesupport (6.0.3.1) lib/active_support/notifications.rb:182:in `instrument'
actionview (6.0.3.1) lib/action_view/template.rb:385:in `instrument_render_template'
actionview (6.0.3.1) lib/action_view/template.rb:183:in `render'
actionview (6.0.3.1) lib/action_view/renderer/partial_renderer.rb:357:in `block in render_partial'
actionview (6.0.3.1) lib/action_view/renderer/abstract_renderer.rb:88:in `block in instrument'
activesupport (6.0.3.1) lib/active_support/notifications.rb:180:in `block in instrument'
activesupport (6.0.3.1) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (6.0.3.1) lib/active_support/notifications.rb:180:in `instrument'
actionview (6.0.3.1) lib/action_view/renderer/abstract_renderer.rb:87:in `instrument'
actionview (6.0.3.1) lib/action_view/renderer/partial_renderer.rb:346:in `render_partial'
actionview (6.0.3.1) lib/action_view/renderer/partial_renderer.rb:317:in `render'
actionview (6.0.3.1) lib/action_view/renderer/renderer.rb:65:in `render_partial_to_object'
actionview (6.0.3.1) lib/action_view/renderer/renderer.rb:27:in `render_to_object'
actionview (6.0.3.1) lib/action_view/renderer/renderer.rb:22:in `render'
actionview (6.0.3.1) lib/action_view/helpers/rendering_helper.rb:34:in `block in render'
actionview (6.0.3.1) lib/action_view/base.rb:304:in `in_rendering_context'
actionview (6.0.3.1) lib/action_view/helpers/rendering_helper.rb:30:in `render'
turbostreamer (d6c4eca5f284) lib/turbostreamer/template.rb:158:in `_render_partial_with_options'
turbostreamer (d6c4eca5f284) lib/turbostreamer/template.rb:34:in `partial!'
app/views/sessions/show.streamer:1
actionview (6.0.3.1) lib/action_view/base.rb:274:in `_run'
actionview (6.0.3.1) lib/action_view/template.rb:185:in `block in render'
activesupport (6.0.3.1) lib/active_support/notifications.rb:182:in `instrument'
actionview (6.0.3.1) lib/action_view/template.rb:385:in `instrument_render_template'
actionview (6.0.3.1) lib/action_view/template.rb:183:in `render'
actionview (6.0.3.1) lib/action_view/renderer/template_renderer.rb:58:in `block (2 levels) in render_template'
actionview (6.0.3.1) lib/action_view/renderer/abstract_renderer.rb:88:in `block in instrument'
activesupport (6.0.3.1) lib/active_support/notifications.rb:180:in `block in instrument'
activesupport (6.0.3.1) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (6.0.3.1) lib/active_support/notifications.rb:180:in `instrument'
actionview (6.0.3.1) lib/action_view/renderer/abstract_renderer.rb:87:in `instrument'
actionview (6.0.3.1) lib/action_view/renderer/template_renderer.rb:57:in `block in render_template'
actionview (6.0.3.1) lib/action_view/renderer/template_renderer.rb:65:in `render_with_layout'
skylight-core (4.2.0) lib/skylight/core/probes/action_view.rb:34:in `render_with_layout'
actionview (6.0.3.1) lib/action_view/renderer/template_renderer.rb:56:in `render_template'
actionview (6.0.3.1) lib/action_view/renderer/template_renderer.rb:13:in `render'
actionview (6.0.3.1) lib/action_view/renderer/renderer.rb:61:in `render_template_to_object'
actionview (6.0.3.1) lib/action_view/renderer/renderer.rb:29:in `render_to_object'
actionview (6.0.3.1) lib/action_view/rendering.rb:117:in `block in _render_template'
actionview (6.0.3.1) lib/action_view/base.rb:304:in `in_rendering_context'
actionview (6.0.3.1) lib/action_view/rendering.rb:116:in `_render_template'
actionpack (6.0.3.1) lib/action_controller/metal/streaming.rb:218:in `_render_template'
actionview (6.0.3.1) lib/action_view/rendering.rb:103:in `render_to_body'
actionpack (6.0.3.1) lib/action_controller/metal/rendering.rb:52:in `render_to_body'
actionpack (6.0.3.1) lib/action_controller/metal/renderers.rb:142:in `render_to_body'
actionpack (6.0.3.1) lib/abstract_controller/rendering.rb:25:in `render'
actionpack (6.0.3.1) lib/action_controller/metal/rendering.rb:36:in `render'
actionpack (6.0.3.1) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
activesupport (6.0.3.1) lib/active_support/core_ext/benchmark.rb:14:in `block in ms'
/usr/local/Cellar/ruby/2.7.1_2/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'
activesupport (6.0.3.1) lib/active_support/core_ext/benchmark.rb:14:in `ms'
actionpack (6.0.3.1) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
actionpack (6.0.3.1) lib/action_controller/metal/instrumentation.rb:84:in `cleanup_view_runtime'
activerecord (6.0.3.1) lib/active_record/railties/controller_runtime.rb:34:in `cleanup_view_runtime'
actionpack (6.0.3.1) lib/action_controller/metal/instrumentation.rb:43:in `render'
app/controllers/sessions_controller.rb:27:in `current'
actionpack (6.0.3.1) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
actionpack (6.0.3.1) lib/abstract_controller/base.rb:195:in `process_action'
actionpack (6.0.3.1) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (6.0.3.1) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
activesupport (6.0.3.1) lib/active_support/callbacks.rb:112:in `block in run_callbacks'
app/controllers/application_controller.rb:274:in `block in set_context'
activesupport (6.0.3.1) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.3.1) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.3.1) lib/active_support/tagged_logging.rb:80:in `tagged'
app/controllers/application_controller.rb:273:in `set_context'
activesupport (6.0.3.1) lib/active_support/callbacks.rb:121:in `block in run_callbacks'
activesupport (6.0.3.1) lib/active_support/callbacks.rb:139:in `run_callbacks'
actionpack (6.0.3.1) lib/abstract_controller/callbacks.rb:41:in `process_action'
actionpack (6.0.3.1) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (6.0.3.1) lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
activesupport (6.0.3.1) lib/active_support/notifications.rb:180:in `block in instrument'
activesupport (6.0.3.1) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (6.0.3.1) lib/active_support/notifications.rb:180:in `instrument'
actionpack (6.0.3.1) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
actionpack (6.0.3.1) lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
activerecord (6.0.3.1) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
actionpack (6.0.3.1) lib/abstract_controller/base.rb:136:in `process'
actionview (6.0.3.1) lib/action_view/rendering.rb:39:in `process'
actionpack (6.0.3.1) lib/action_controller/metal.rb:190:in `dispatch'
actionpack (6.0.3.1) lib/action_controller/metal.rb:254:in `dispatch'
actionpack (6.0.3.1) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
actionpack (6.0.3.1) lib/action_dispatch/routing/route_set.rb:33:in `serve'
actionpack (6.0.3.1) lib/action_dispatch/journey/router.rb:49:in `block in serve'
actionpack (6.0.3.1) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (6.0.3.1) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (6.0.3.1) lib/action_dispatch/routing/route_set.rb:834:in `call'
skylight-core (4.2.0) lib/skylight/core/probes/action_dispatch/routing/route_set.rb:14:in `block in call'
skylight-core (4.2.0) lib/skylight/core/fanout.rb:25:in `instrument'
skylight-core (4.2.0) lib/skylight/core/probes/action_dispatch/routing/route_set.rb:13:in `call'
rack (2.2.2) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.2.2) lib/rack/etag.rb:27:in `call'
rack (2.2.2) lib/rack/conditional_get.rb:27:in `call'
rack (2.2.2) lib/rack/head.rb:12:in `call'
actionpack (6.0.3.1) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.2.2) lib/rack/session/abstract/id.rb:266:in `context'
rack (2.2.2) lib/rack/session/abstract/id.rb:260:in `call'
actionpack (6.0.3.1) lib/action_dispatch/middleware/cookies.rb:648:in `call'
activerecord (6.0.3.1) lib/active_record/migration.rb:567:in `call'
actionpack (6.0.3.1) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.3.1) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.3.1) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.3.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.1) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
actionpack (6.0.3.1) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
actionpack (6.0.3.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.3.1) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.3.1) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.3.1) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.3.1) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.3.1) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.3.1) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.3.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.3.1) lib/action_dispatch/middleware/request_id.rb:27:in `call'
skylight-core (4.2.0) lib/skylight/core/probes/action_dispatch/request_id.rb:12:in `call'
standardapi (2b3ec1e8ac2a) lib/standard_api/middleware/query_encoding.rb:29:in `call'
rack (2.2.2) lib/rack/method_override.rb:24:in `call'
rack (2.2.2) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.3.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.3.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.1) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.2) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.3.1) lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
railties (6.0.3.1) lib/rails/engine.rb:527:in `call'
puma (3.12.2) lib/puma/configuration.rb:227:in `call'
puma (3.12.2) lib/puma/server.rb:674:in `handle_request'
puma (3.12.2) lib/puma/server.rb:476:in `process_client'
puma (3.12.2) lib/puma/server.rb:334:in `block in run'
puma (3.12.2) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
```
